### ISSUE TITLE
Dynamic actions don't work

### ISSUE THREAD

**Issue by itsViney** [farzadso/Simple-Checkbox-2--With-Bootstrap-Switch-#1]
Simple Checkbox 2 does appear to work correctly with dynamic actions.

With these item settings:
![item params](https://cloud.githubusercontent.com/assets/2415212/20663322/e97ed38c-b54e-11e6-9cef-92083246de74.png)

...and this dynamic action:
![da params](https://cloud.githubusercontent.com/assets/2415212/20663387/3e52c4b8-b54f-11e6-9bd1-172c99006bc3.png)

...these actions don't fire:
![da true](https://cloud.githubusercontent.com/assets/2415212/20663518/ac4208a8-b54f-11e6-909b-0703f5ac0f74.png)
![da false](https://cloud.githubusercontent.com/assets/2415212/20663519/ac42d580-b54f-11e6-9a50-85c137e3b4a9.png)

**Comment by farzadso** [comment]
Hi,

Sorry for the late reply. I was working on fixing this problem.

Redownload the package, as I have added a custom Change event which you can select in your dynamic actions. Here is a screenshot : 

![image](https://cloud.githubusercontent.com/assets/19854715/20874167/91bd772c-bac4-11e6-91aa-1d192e0f86d6.png)
