### ISSUE TITLE
No change or click event for dynamic action

### ISSUE THREAD

**Issue by hairpin666** [farzadso/Simple-Checkbox-2--With-Bootstrap-Switch-#2]
There is no event fired when a dynamic action is set to the toggle element. Neither onChange nor onClick works.

**Comment by farzadso** [comment]
Redownload the package, as I have added a custom Change event which you can select in your dynamic actions. Here is a screenshot :
![image](https://cloud.githubusercontent.com/assets/19854715/24894994/1c1390b8-1ea3-11e7-8339-de109f7d4f5a.png)
