### ISSUE TITLE
Dynamic Action - Condition not recognised

### ISSUE THREAD

**Issue by hairpin666** [farzadso/Simple-Checkbox-2--With-Bootstrap-Switch-#3]
Hi,

It seems like the condition for the Switch Dynamic Action is not being recognised. When I switch the toggle with acitvated Dynamic Action and condition set to "equal to" it is not fired correctly.

Is there a quick way to fix it?

Thanks

**Comment by farzadso** [comment]
Hi, Sorry for the late reply, 

I just tested it and it's working with no issues at all. 
![image](https://cloud.githubusercontent.com/assets/19854715/25783966/65b12c12-337a-11e7-8f75-b580b9123060.png)

What version of the plugin are you using ? Make sure you're on v1.3 :

![image](https://cloud.githubusercontent.com/assets/19854715/25783975/7d7241d8-337a-11e7-8aa9-ea7b3830471d.png)

**Comment by hairpin666** [comment]
Hi,

Does not seem to work for me, I'm using v1.3 and Apex Version:  5.0.4.00.12.

I managed to get the DA to work but it always fires the "FALSE" action.

See my settings below:

![unbenannt](https://cloud.githubusercontent.com/assets/16673188/25796239/073ed724-33d9-11e7-98d3-9f40e974af17.PNG)

![unbenannt2](https://cloud.githubusercontent.com/assets/16673188/25796271/282a8e24-33d9-11e7-853d-ee9ebd48e57d.PNG)

**Comment by itsViney** [comment]
I've got the same issue running version 1.4 of the plugin. Always seems to return false.

**Comment by DanielWenz** [comment]
For me it does not submit the value to a pl/sql code inside a DA too

**Comment by BarryBrierley** [comment]
+1 for PL/SQL does not recognize value. Apex 18

**Comment by farzadso** [comment]
@BarryBrierley Hi, Unfortunately, I don't work with Oracle APEX anymore and I won't be maintaining this plugin anymore.

I will respond to any merge requests though.
